name: obscuro_map
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.1.0
  go_router_builder: ^4.2.0
  flutter_svg: ^2.2.3
  vector_graphics: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  flutter_gen_runner: ^5.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/features/splash/

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true
    image: true
    rive: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/app_logo.svg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/launcher/app_logo.svg"